title:        "Zápisník Josefa Rouska"
subtitle:     "Python a React.js programátor, zaměřený na Shopify integrace"
url:          https://blog.rousek.name
author:
  name:       "Josef Rousek"
  email:      "josef.rousek@gmail.com"
markdown:     kramdown
permalink:    pretty
