title:        "Zápisník Josefa Rouska"
subtitle:     "Python a React.js programátor, zaměřený na Shopify integrace"
url:          http://blog.rousek.name
author:
  name:       "Josef Rousek"
  email:      "josef.rousek@gmail.com"
markdown:     kramdown
permalink:    pretty
highlighter:  pygments

analytics:
  google:
    id:       "UA-485461-7"
